services:
  - type: worker
    name: string-session-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install psycopg2-binary
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: string-session-db
          property: connectionString
      - key: MUST_JOIN
        value: ""
      - key: SUPPORT_CHAT
        value: ""

databases:
  - name: string-session-db
    databaseName: string_session
    plan: free